name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build, Vet & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: "go.sum"

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -race -coverprofile=coverage.out
        # Redis will be added later for Collector tests

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: "go.sum"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest